#161255353 - User Signup/Registration validation errors
andela/ah-codeofduty pull request #10
Opened 2018-10-30 08:06 UTC by AnguleMathias

#### What does this PR do?
* Users are able to receive descriptive signup/Registration validation errors

#### Description of Task to be completed
* Users should receive descriptive error messages upon signing up with invalid user parameters 
* Invalid user parameters include:
                  i.   Existing user email
                  ii.  Invalid email
                  iii. Password of length less than 8
                  iv. Password not being alphanumeric

#### How should this be manually tested?
* Run app by : `python3 migrate.py runserver` in terminal
* Use postman on end-route: `api/users/`
* Signup/Register user(s)

#### What are the relevant pivotal tracker stories?
* #161255353 - [Users should receive descriptive signup/Registration validation errors](https://www.pivotaltracker.com/story/show/161255353)

2018-10-30 08:50 UTC, meshnesh requested changes
<img width="1142" alt="screen shot 2018-10-30 at 11 48 37" src="https://user-images.githubusercontent.com/15923109/47706243-cae43480-dc39-11e8-8e09-6c8c30bb4aa9.png">
Passwords should not accept repetitive letters.

2018-10-31 08:32 UTC, maxwellgithinji approved these changes
LGTM

2018-10-31 08:39 UTC, meshnesh approved these changes

2018-10-31 08:52 UTC, Jwesh approved these changes
good job

2018-10-31 08:56 UTC, merged