#161255356 - Social login
andela/ah-codeofduty pull request #14
Opened 2018-11-01 13:06 UTC by KITHU

#### What does this PR do?
* Enable Social login via Google, Facebook and Twitter
#### Description of Task to be completed?
* Currently a new user cannot login with their pre-existing social media accounts. He/She can only register and or login with email password combinations
#### How should this be manually tested?
1. clone the repo and switch to ft-social-login-161255356
2. set environment and also configure database 
3. get token from google [developer playground](https://developers.google.com/oauthplayground/)
4. get token from facebook [developer console](https://developers.facebook.com/apps/541475206299733/roles/test-users/)

#### Any background context you want to provide?
* social login improves user experience while using the application.
#### What are the relevant pivotal tracker stories?
* Enable Social login via Google, Facebook and Twitter-[161255356](https://www.pivotaltracker.com/story/show/161255356)
#### Screenshots
<img width="964" alt="screen shot 2018-11-01 at 14 13 19" src="https://user-images.githubusercontent.com/17101765/47853392-9fa34600-ddef-11e8-9693-fbf072c7c9b6.png">

2018-11-01 13:47 UTC, AnguleMathias approved these changes
Looks great! 
Check on test coverage.

2018-11-02 07:52 UTC, meshnesh requested changes
Write test for the added code to increase the coverage

2018-11-05 12:11 UTC, njeri-ngigi approved these changes

2018-11-05 12:15 UTC, maxwellgithinji approved these changes
LGTM

2018-11-05 12:41 UTC, AnguleMathias approved these changes

2018-11-05 12:43 UTC, meshnesh approved these changes

2018-11-05 12:43 UTC, meshnesh requested changes
Fix the failing test.

2018-11-05 12:52 UTC, meshnesh commented on authors/apps/authentication/backends.py
> +            'email': email,
Is the token supposed to be encoded with the `email` or `user_id`?

2018-11-06 06:55 UTC, meshnesh approved these changes

2018-11-06 06:55 UTC, merged